"""removing foreign key created by

Revision ID: 858ae538f0b4
Revises: 555710aa4e42
Create Date: 2022-02-27 10:39:46.507899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '858ae538f0b4'
down_revision = '555710aa4e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_ibfk_1', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###
