"""remove created by column

Revision ID: b49d144db9c2
Revises: ebb5138cedfd
Create Date: 2022-07-16 16:32:29.735942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b49d144db9c2'
down_revision = 'ebb5138cedfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ticket_management_ibfk_1', 'user_ticket_management', type_='foreignkey')
    op.drop_column('user_ticket_management', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_ticket_management', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_ticket_management_ibfk_1', 'user_ticket_management', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###
