"""make column nullable

Revision ID: ff97a3226a72
Revises: ff527d5edea3
Create Date: 2022-07-16 12:32:39.194518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff97a3226a72'
down_revision = 'ff527d5edea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'supervised_by',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'supervised_by',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
